### ISSUE TITLE
Transient test failures

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#1248]
```
$ ./test
Building fleetd...
Building fleetctl...
Running tests...
ERROR reconcile.go:253: Desired state and current state of Job(foo.service) nil, not sure what to do
ERROR reconcile.go:253: Desired state and current state of Job(foo.service) nil, not sure what to do
ERROR unit_state.go:224: Refusing to push UnitState(foo.service), no MachineID: &unit.UnitState{LoadState:"", ActiveState:"active", SubState:"", MachineID:"", UnitHash:"", UnitName:"foo.service"}
--- FAIL: TestUnitStatePublisherRunWithDelays-2 (0.00 seconds)
	unit_state_test.go:626: bad published UnitStates: got []string{"0.service", "2.service", "4.service", "1.service", "3.service"}, want []string{"0.service", "1.service", "2.service", "3.service", "4.service"}
	unit_state_test.go:640: bad published UnitStates: got []string{"0.service", "2.service", "4.service", "1.service", "3.service"}, want []string{"0.service", "1.service", "2.service", "3.service", "4.service"}
	unit_state_test.go:658: bad UnitStates: got []string{"foo.service", "baz.service", "bar.service"}, want []string{"foo.service", "bar.service", "baz.service"}
FAIL
coverage: 70.6% of statements
FAIL	github.com/coreos/fleet/agent	0.009s
ok  	github.com/coreos/fleet/api	0.010s	coverage: 80.4% of statements
ok  	github.com/coreos/fleet/config	0.004s	coverage: 100.0% of statements
ok  	github.com/coreos/fleet/engine	0.009s	coverage: 54.5% of statements
ok  	github.com/coreos/fleet/fleetctl	0.010s	coverage: 23.3% of statements
ok  	github.com/coreos/fleet/job	0.009s	coverage: 89.2% of statements
ok  	github.com/coreos/fleet/machine	0.007s	coverage: 35.1% of statements
ok  	github.com/coreos/fleet/pkg	0.009s	coverage: 81.9% of statements
ok  	github.com/coreos/fleet/pkg/lease	0.006s	coverage: 14.3% of statements
ok  	github.com/coreos/fleet/registry	0.008s	coverage: 26.7% of statements
ok  	github.com/coreos/fleet/ssh	0.009s	coverage: 42.5% of statements
ok  	github.com/coreos/fleet/systemd	0.006s	coverage: 15.5% of statements
ok  	github.com/coreos/fleet/unit	0.037s	coverage: 88.4% of statements
```

**Comment by bcwaldon** [comment]
Seeing this every once in a while on travis. This failure was from https://travis-ci.org/coreos/fleet/jobs/66578356

**Comment by crawford** [comment]
Here's another: https://travis-ci.org/coreos/fleet/jobs/67288307

**Comment by mischief** [comment]
i can't reproduce this at all locally, but lately it happens repeatedly on travis-ci. :-1:

**Comment by mischief** [comment]
can reproduce with GOMAXPROCS > 1. there's also a nice deadlock..

```
$ PKG=agent ./test -run TestUnitStatePublisherRunWithDelays
Building fleetd...
Building fleetctl...
Running tests...
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.RunTests(0x80af70, 0x910c80, 0x12, 0x12, 0x7c9001)
        /home/mischief/go1.4/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20804a320, 0x91b660)
        /home/mischief/go1.4/go/src/testing/testing.go:485 +0x6c
main.main()
        github.com/coreos/fleet/agent/_test/_testmain.go:142 +0x291

goroutine 5 [semacquire]:
sync.(*WaitGroup).Wait(0xc20800a4c0)
        /home/mischief/go1.4/go/src/sync/waitgroup.go:132 +0x169
github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays(0xc20806a1b0)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:621 +0x115e
testing.tRunner(0xc20806a1b0, 0x910de8)
        /home/mischief/go1.4/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /home/mischief/go1.4/go/src/testing/testing.go:555 +0xa8b

goroutine 6 [select]:
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run(0xc208084080, 0xc208056360, 0xc2080563c0)
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:128 +0x3df
github.com/coreos/fleet/agent.func·017()
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:568 +0x43
created by github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:569 +0x6a5

goroutine 17 [select]:
github.com/coreos/fleet/agent.func·008()
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:73 +0x296
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:89 +0xf5

goroutine 18 [chan receive]:
github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork.(*fakeClock).Sleep(0xc208056240, 0xb2d05e00)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork/clockwork.go:115 +0x55
github.com/coreos/fleet/agent.func·016(0x780970, 0xb, 0xc20809a1e0)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:548 +0x74
github.com/coreos/fleet/agent.func·009()
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:118 +0x27f
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:122 +0x1fe

goroutine 19 [chan receive]:
github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork.(*fakeClock).Sleep(0xc208056240, 0xb2d05e00)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork/clockwork.go:115 +0x55
github.com/coreos/fleet/agent.func·016(0x77dd30, 0xb, 0xc20809a120)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:548 +0x74
github.com/coreos/fleet/agent.func·009()
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:118 +0x27f
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:122 +0x1fe

goroutine 20 [select]:
github.com/coreos/fleet/agent.func·009()
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:100 +0x2aa
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:122 +0x1fe

goroutine 21 [chan receive]:
github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork.(*fakeClock).Sleep(0xc208056240, 0xb2d05e00)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork/clockwork.go:115 +0x55
github.com/coreos/fleet/agent.func·016(0xc20802aa70, 0x9, 0xc208056600)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:548 +0x74
github.com/coreos/fleet/agent.func·009()
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:118 +0x27f
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:122 +0x1fe

goroutine 22 [chan receive]:
github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork.(*fakeClock).Sleep(0xc208056240, 0xb2d05e00)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork/clockwork.go:115 +0x55
github.com/coreos/fleet/agent.func·016(0x77dd90, 0xb, 0xc20809a180)
        /mnt/host/source/src/third_party/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:548 +0x74
github.com/coreos/fleet/agent.func·009()
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:118 +0x27f
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
        github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:122 +0x1fe
FAIL    github.com/coreos/fleet/agent   0.006s
```

**Comment by mischief** [comment]
there seems to have been a number of races in the agent tests, the last of which i believe is following:

```
$ PKG=agent ./test
Building fleetd...
Building fleetctl...
Running tests...
ERROR reconcile.go:265: Desired state and current state of Job(foo.service) nil, not sure what to do
ERROR reconcile.go:265: Desired state and current state of Job(foo.service) nil, not sure what to do
ERROR unit_state.go:243: Refusing to push UnitState(foo.service), no MachineID: &unit.UnitState{LoadState:"", ActiveState:"active", SubState:"", MachineID:"", UnitHash:"", UnitName:"foo.service"}
--- FAIL: TestUnitStatePublisherRunWithDelays-4 (0.00s)
        unit_state_test.go:650: bad toPublishStates: got map[string]*unit.UnitState{"bar.service":(*unit.UnitState)(0xc2080a06c0), "foo.service":(*unit.UnitState)(0xc2080a0660), "baz.service":(*unit.UnitState)(0xc2080a0720)}, want map[string]*unit.UnitState{"bar.service":(*unit.UnitState)(0xc2080a0840), "baz.service":(*unit.UnitState)(0xc2080a08a0), "foo.service":(*unit.UnitState)(0xc2080a07e0)}
FAIL
coverage: 70.6% of statements
FAIL    github.com/coreos/fleet/agent   0.007s
```

**Comment by jonboulle** [comment]
The ordering of https://github.com/coreos/fleet/blob/1eebf3bead8dfdd25c1debe317b97658523257f4/agent/unit_state_test.go#L620-L626 is significant yet since they're all goroutines there's no guarantee they'll be scheduled that way. Not sure yet about a solution; ideally we would run them consecutively until they block here - https://github.com/coreos/fleet/blob/1eebf3bead8dfdd25c1debe317b97658523257f4/agent/unit_state.go#L167

**Comment by marineam** [comment]
For now I tossed in a Skip in https://github.com/coreos/fleet/pull/1354
