### ISSUE TITLE
exception in fleet/systemd - panic: runtime error: close of closed channel

### ISSUE THREAD

**Issue by mwhooker** [coreos/fleet#1284]
Occasionally seeing this exception when calling `systemd.NewSystemdUnitManager`

```
sh[1790]: panic: runtime error: close of closed channel
sh[1790]: goroutine 18156 [running]:
sh[1790]: runtime.panic(0x887220, 0xb8feb5)
sh[1790]: /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
sh[1790]: github.com/coreos/fleet/Godeps/_workspace/src/github.com/godbus/dbus.(*Conn).Close(0xc20832a360, 0x0, 0x0)
sh[1790]: /home/ubuntu/go/src/github.com/wercker/kp/_vendor/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/godbus/dbus/conn.go:178 +0x61
sh[1790]: github.com/coreos/fleet/Godeps/_workspace/src/github.com/godbus/dbus.(*Conn).inWorker(0xc20832a360)
sh[1790]: /home/ubuntu/go/src/github.com/wercker/kp/_vendor/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/godbus/dbus/conn.go:330 +0xfe9
sh[1790]: created by github.com/coreos/fleet/Godeps/_workspace/src/github.com/godbus/dbus.(*Conn).Auth
sh[1790]: /home/ubuntu/go/src/github.com/wercker/kp/_vendor/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/godbus/dbus/auth.go:118 +0xd2a
...
```

The version should be latest from master (43aee47be00b5f4bf60882ee27b7d71ba114a674)

Will try to find a reproduceable example

**Comment by mischief** [comment]
@mwhooker if you can post a reproducible example that would be awesome. it might just be that the godep'd go-systemd needs to be synchronized again.

**Comment by jonboulle** [comment]
+1, seems this is almost certainly https://github.com/godbus/dbus/commit/713a87117602c19f26479c2fb6a2be978e40cb20

**Comment by mwhooker** [comment]
Ah yes, the version of godbus doesn't have the patch. I'll try my hand as syncing the godeps and making a PR

**Comment by jonboulle** [comment]
thanks!
