### ISSUE TITLE
fleetd startup crash when giving weird args

### ISSUE THREAD

**Issue by miekg** [coreos/fleet#1360]
```
~/downloads/fleet-v0.11.5-linux-amd64  
% ./fleetd fdsjkfd
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4020b2]

goroutine 1 [running]:
main.main()
	/home/mischief/code/go/src/github.com/coreos/fleet/fleet/gopath/src/github.com/coreos/fleet/fleetd/fleetd.go:55 +0x14b2

goroutine 2 [runnable]:
runtime.forcegchelper()
	/home/mischief/go/src/runtime/proc.go:90
runtime.goexit()
	/home/mischief/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/home/mischief/go/src/runtime/mgc0.go:82
runtime.goexit()
	/home/mischief/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/home/mischief/go/src/runtime/malloc.go:712
runtime.goexit()
	/home/mischief/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
os/signal.loop()
	/home/mischief/go/src/os/signal/signal_unix.go:19
created by os/signal.init·1
	/home/mischief/go/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by jonboulle** [comment]
Introduced by 8ebb81bcd1668be4a874db98cbf2e67ae305d7f6

**Comment by ianbytchek** [comment]
I'm getting the same thing with a slightly different message.

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40245e]

goroutine 1 [running]:
main.main()
	/build/amd64-usr/var/tmp/portage/app-admin/fleet-0.11.5-r1/work/gopath/src/github.com/coreos/fleet/fleetd/fleetd.go:55 +0x145e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [runnable]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by sheerun** [comment]
It's still a thing for  0.11.5. e.g. `fleetd asdfa`

**Comment by tixxdz** [comment]
@sheerun in git master it's fixed, so I guess we should just wait for the next release soon. thanks!
