### ISSUE TITLE
Fleet suddenly failed after a night of working

### ISSUE THREAD

**Issue by ianbytchek** [coreos/fleet#1380]
On latest CoreOS alpha.

```sh
$ fleetctl list-units
[signal 0xb code=0x1 addr=0x0 pc=0x40245e]

goroutine 1 [running]:
main.main()
        /build/amd64-usr/var/tmp/portage/app-admin/fleet-0.11.5-r1/work/gopath/src/github.com/coreos/fleet/fleetd/fleetd.go:55 +0x145e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [runnable]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by jonboulle** [comment]
Sorry for the delay. I'm a bit confused by your report since it seems to involve both fleetctl and fleetd?

**Comment by jonboulle** [comment]
hmm, is this mixed with https://github.com/coreos/fleet/issues/1360 ?

**Comment by ianbytchek** [comment]
Sorry, must be a duplicate, I thought it's might be the same but didn't notice a difference.
