### ISSUE TITLE
github.com/coreos/fleet/agent unit test fail with one cpu

### ISSUE THREAD

**Issue by reneengelhard** [coreos/fleet#1434]
When doing stuff on #1430 I also tried to run the unit tests and they failed for me.

```
core@core-01 ~/fleet $ ./test
Building fleetd...
Building fleetctl...
Running tests...
ERROR reconcile.go:265: Desired state and current state of Job(foo.service) nil, not sure what to do
ERROR reconcile.go:265: Desired state and current state of Job(foo.service) nil, not sure what to do
ERROR unit_state.go:243: Refusing to push UnitState(foo.service), no MachineID: &unit.UnitState{LoadState:"", ActiveState:"active", SubState:"", MachineID:"", UnitHash:"", UnitName:"foo.service"}
panic: sync: negative WaitGroup counter

goroutine 88 [running]:
sync.(*WaitGroup).Add(0xc8200ed450, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:70 +0xd0
sync.(*WaitGroup).Done(0xc8200ed450)
	/usr/local/go/src/sync/waitgroup.go:95 +0x2a
github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays.func1(0x7e08e0, 0xb, 0xc820100f60)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:580 +0x54
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc8201009c0, 0xc820082c00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 1 [chan receive]:
testing.RunTests(0x8768e8, 0x99ec00, 0x12, 0x12, 0xc820070701)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820045ef8, 0x9a21a0)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/coreos/fleet/agent/_test/_testmain.go:144 +0x252

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 84 [semacquire]:
sync.runtime_Semacquire(0xc8200ed46c)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8200ed460)
	/usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays(0xc8200735f0)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:672 +0x15c9
testing.tRunner(0xc8200735f0, 0x99ed68)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 87 [chan receive]:
github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork.(*fakeClock).Sleep(0xc820100840, 0xb2d05e00)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork/clockwork.go:115 +0x4e
github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays.func1(0x7dee70, 0xb, 0xc820100f00)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:582 +0x72
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc8201009c0, 0xc820082c00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 86 [select]:
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func1(0xc8201009c0, 0xc820082c00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:80 +0x28b
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:96 +0x5e

goroutine 91 [chan receive]:
github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork.(*fakeClock).Sleep(0xc820100840, 0xb2d05e00)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork/clockwork.go:115 +0x4e
github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays.func1(0x7dee20, 0xb, 0xc820100ea0)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:582 +0x72
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc8201009c0, 0xc820082c00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 90 [chan receive]:
github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork.(*fakeClock).Sleep(0xc820100840, 0xb2d05e00)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork/clockwork.go:115 +0x4e
github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays.func1(0x7e08e0, 0xb, 0xc820100e40)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:582 +0x72
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc8201009c0, 0xc820082c00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 89 [runnable]:
github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork.(*fakeClock).Sleep(0xc820100840, 0xb2d05e00)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork/clockwork.go:115 +0x4e
github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays.func1(0xc8200ed5b0, 0x9, 0xc820100cc0)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:582 +0x72
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc8201009c0, 0xc820082c00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 71 [select]:
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run(0xc820082b00, 0xc8201001e0, 0xc820100240)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:135 +0x2dc
github.com/coreos/fleet/agent.TestUnitStatePublisherRunQueuing.func2(0xc820082b00, 0xc8201001e0, 0xc820100240)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:471 +0x35
created by github.com/coreos/fleet/agent.TestUnitStatePublisherRunQueuing
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:472 +0x503

goroutine 72 [select]:
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func1(0xc820100240, 0xc820082b00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:80 +0x28b
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:96 +0x5e

goroutine 73 [chan receive]:
github.com/coreos/fleet/agent.TestUnitStatePublisherRunQueuing.func1(0xc8200ed140, 0x9, 0xc8201002a0)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:448 +0x62
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc820100240, 0xc820082b00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 74 [chan receive]:
github.com/coreos/fleet/agent.TestUnitStatePublisherRunQueuing.func1(0xc8200ed180, 0x9, 0xc8201003c0)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:448 +0x62
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc820100240, 0xc820082b00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 75 [chan receive]:
github.com/coreos/fleet/agent.TestUnitStatePublisherRunQueuing.func1(0xc8200ed160, 0x9, 0xc820100360)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:448 +0x62
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc820100240, 0xc820082b00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 76 [chan receive]:
github.com/coreos/fleet/agent.TestUnitStatePublisherRunQueuing.func1(0xc8200ed1c0, 0x9, 0xc820100480)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:448 +0x62
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc820100240, 0xc820082b00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 77 [chan receive]:
github.com/coreos/fleet/agent.TestUnitStatePublisherRunQueuing.func1(0xc8200ed1a0, 0x9, 0xc820100420)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:448 +0x62
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run.func2(0xc820100240, 0xc820082b00)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:125 +0x254
created by github.com/coreos/fleet/agent.(*UnitStatePublisher).Run
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:129 +0x10b

goroutine 85 [select]:
github.com/coreos/fleet/agent.(*UnitStatePublisher).Run(0xc820082c00, 0xc820100960, 0xc8201009c0)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:135 +0x2dc
github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays.func2(0xc820082c00, 0xc820100960, 0xc8201009c0)
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:608 +0x35
created by github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:609 +0x724

goroutine 95 [runnable]:
github.com/coreos/fleet/agent.(*UnitStatePublisher).queueForPublish(0xc820082c00, 0x7e08e0, 0xb, 0xc820100f60)
	github.com/coreos/fleet/agent/_test/_obj_test/unit_state.go:190 +0xe5
created by github.com/coreos/fleet/agent.TestUnitStatePublisherRunWithDelays
	/home/core/fleet/gopath/src/github.com/coreos/fleet/agent/unit_state_test.go:630 +0xb25
FAIL	github.com/coreos/fleet/agent	0.008s
```

Intesrestingly, when I changed my vagrant configuration from 1 CPU/1024 MB RAM to 2 CPUs/1024 MB RAM the test succeeds without any further changes.

While looking into that we noticed that the line numbers mentioned in the first part above are not there in the files in the actual tree, e.g.

```
core@core-01 ~/fleet $ wc -l agent/unit_state.go 
223 agent/unit_state.go
```

So the test seems to use the "old" CoreOS /usr/bin/fleetd and /usr/bin/fleetctl? (which probably warrants an other issue, though)

**Comment by jonboulle** [comment]
This rings a vague bell but ISTRC it's a problem with how go builds and runs the tests (and loses the appropriate line information)

**Comment by jonboulle** [comment]
@reneengelhard are you looking into this one?

**Comment by reneengelhard** [comment]
@jonboulle: not sure, I guess someone with longer understaing of what it is supposed to do would be better at that. especially when it already rings a bell.

**Comment by reneengelhard** [comment]
@jonboulle At least I see afb00d93e79b27ea9e0799adafff6ebc9808121c which claims that the test is broken with != 1, whereas we see it breaking with 1 and working with e.g. 2.

When doing

`diff --git a/agent/unit_state_test.go b/agent/unit_state_test.go
index 3c58c4d..86532e5 100644
--- a/agent/unit_state_test.go
+++ b/agent/unit_state_test.go
@@ -569,8 +569,8 @@ func TestUnitStatePublisherRunQueuing(t *testing.T) {
 }
 
 func TestUnitStatePublisherRunWithDelays(t *testing.T) {
-       if runtime.GOMAXPROCS(-1) != 1 {
-               t.Skipf("Broken for GOMAXPROCS != 1, currently %d", runtime.GOMAXPROCS(-1))
+       if runtime.GOMAXPROCS(-1) == 1 {
+               t.Skipf("Broken for GOMAXPROCS == 1, currently %d", runtime.GOMAXPROCS(-1))
        }
        states := make([]string, 0)
        mu := sync.Mutex{} // protects states from concurrent modification
`

it works:

`Building fleetd...
Building fleetctl...
Running tests...
ok  	github.com/coreos/fleet/agent	0.004s	coverage: 70.0% of statements
[...]`

**Comment by reneengelhard** [comment]
and this commit was for #1248 which sounds like exactly this one

**Comment by reneengelhard** [comment]
or not..

**Comment by jonboulle** [comment]
@reneengelhard Any chance you can try against different go versions? this would have been ~1.4 at the time this happened, wouldn't be entirely surprising if something changed in the scheduling between then and 1.5/1.6

**Comment by reneengelhard** [comment]
can try

**Comment by reneengelhard** [comment]
@jonboulle ok, I tried it:

(with a hacked install_go.sh to specify the go version as first argument)

`
core@core-01 ~/fleet $ export goversions="1.4 1.4.1 1.4.2 1.4.3 1.5 1.5.1 1.5.2 1.5.3 1.6"; for i in $goversions; do ./functional/provision/install_go.sh $i; export GOROOT=~/go; ~/go/bin/go version; ./test; rm -rf ~/go; done 2>&1
`

See https://gist.github.com/reneengelhard/642e092948259391de28. So it works with 1.4 for me and with 1.5+ it fails

**Comment by reneengelhard** [comment]
rerunning now with the condition changed to ==. just for cross-checking

**Comment by reneengelhard** [comment]
oops, sorry, noticed I never actually posted this...

that one of course skips the test then... so with a new VM with 2 CPUs:

https://gist.github.com/reneengelhard/9f94e6854a5cf347b800

**Comment by dongsupark** [comment]
Hopefully fixed via https://github.com/coreos/fleet/pull/1651. Closing.
